# Generated by Django 6.0.6 on 2026-07-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewmessage',
            old_name='tranascript_text',
            new_name='transcript_text',
        ),
        migrations.RenameField(
            model_name='interviewsession',
            old_name='overall_scrore',
            new_name='overall_score',
        ),
    ]
