# Generated by Django 6.0.6 on 2026-07-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_rename_tranascript_text_interviewmessage_transcript_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewmessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
